"use client"

import Navbar from '../component/navbar/Navbar'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import { store } from '../GlobalRedux/store'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body>
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  )
}
